"use client";
import { useEffect, useMemo, useState } from "react";

type Task = { id:number; title:string; unit:string; priority:string; status:string; progress:number; deadline:string; extendedDeadline:string; verificationStatus:string; notes:string; output:string };
const TASK_STATUSES = ["Semua","Baru","Ditolak","Dikerjakan","Menunggu Verifikasi","Verifikasi Final","Perbaikan","Selesai"];

export default function MonitoringCenter(){
  const [rows,setRows]=useState<Task[]>([]),[scope,setScope]=useState(""),[q,setQ]=useState(""),[unit,setUnit]=useState("Semua"),[status,setStatus]=useState("Semua"),[priority,setPriority]=useState("Semua"),[deadline,setDeadline]=useState("Semua");
  useEffect(()=>{fetch("/api/monitoring").then(r=>r.json()).then(d=>{setRows(d.tasks||[]);setScope(d.scope||"")})},[]);
  const today=new Date().toISOString().slice(0,10);
  const condition=(t:Task)=>{const end=t.extendedDeadline||t.deadline;if(!end)return"Tanpa Deadline";if(end<today&&t.status!=="Selesai")return"Terlambat";if(t.extendedDeadline)return"Diperpanjang";return"Aman"};
  const units=["Semua",...Array.from(new Set(rows.map(x=>x.unit)))];
  const filtered=useMemo(()=>rows.filter(t=>(!q||t.title.toLowerCase().includes(q.toLowerCase()))&&(unit==="Semua"||t.unit===unit)&&(status==="Semua"||t.status===status)&&(priority==="Semua"||t.priority===priority)&&(deadline==="Semua"||condition(t)===deadline)),[rows,q,unit,status,priority,deadline]);
  const stat=(s:string)=>rows.filter(t=>s==="Aktif"?t.status!=="Selesai":condition(t)===s).length;
  const avg=rows.length?Math.round(rows.reduce((a,b)=>a+b.progress,0)/rows.length):0;
  return <section className="monitor-page"><div className="page-title"><div><p>DASHBOARD KEPUTUSAN</p><h1>Monitoring To-Do</h1><span>Cakupan: {scope||"memuat kewenangan..."}</span></div></div><div className="monitor-metrics"><article><b>{stat("Aktif")}</b><span>Pekerjaan aktif</span></article><article><b>{avg}%</b><span>Rata-rata progres</span></article><article><b>{stat("Terlambat")}</b><span>Melewati deadline</span></article><article><b>{rows.filter(t=>t.status==="Menunggu Verifikasi"||t.status==="Verifikasi Final").length}</b><span>Menunggu verifikasi</span></article></div><div className="monitor-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari uraian pekerjaan..."/><select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}>{TASK_STATUSES.map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}>{["Semua","Rendah","Sedang","Tinggi","Urgent"].map(x=><option key={x}>{x}</option>)}</select><select value={deadline} onChange={e=>setDeadline(e.target.value)}>{["Semua","Aman","Terlambat","Diperpanjang","Tanpa Deadline"].map(x=><option key={x}>{x}</option>)}</select></div><div className="monitor-table"><table><thead><tr><th>Pekerjaan</th><th>Subbagian</th><th>Prioritas</th><th>Status</th><th>Progres</th><th>Deadline</th><th>Kondisi</th><th>Verifikasi</th></tr></thead><tbody>{filtered.length?filtered.map(t=><tr key={t.id}><td><b>{t.title}</b><small>{t.notes||"Tanpa catatan"}</small></td><td>{t.unit}</td><td>{t.priority}</td><td>{t.status}</td><td><div className="mini-progress"><i style={{width:`${t.progress}%`}}/></div>{t.progress}%</td><td>{t.extendedDeadline||t.deadline||"—"}</td><td><span className={`condition ${condition(t).toLowerCase()}`}>{condition(t)}</span></td><td>{t.verificationStatus}</td></tr>):<tr><td colSpan={8} className="empty-state">Belum ada pekerjaan yang sesuai dengan filter dan kewenangan Anda.</td></tr>}</tbody></table></div></section>
}
