"use client";
import { useEffect, useMemo, useState } from "react";

type Employee={id:number;fullName:string;position:string;unitSubsection:string};
type Coordination={id:number;commissionerEmployeeId:number;unitSubsection:string};
type Unit={id:number;name:string;type:string;parentId:number|null;leaderEmployeeId:number|null;sortOrder:number;status:"Aktif"|"Nonaktif"};
type Position={id:number;name:string;level:"Ketua"|"Anggota"|"Sekretaris"|"Kasubag"|"Staf";unitId:number;reportsToPositionId:number|null;sortOrder:number;status:"Aktif"|"Nonaktif";assignedEmployeeId:number|null;assignedEmployeeName:string|null};
const unitBlank={name:"",type:"Unit",parentId:null as number|null,sortOrder:0,status:"Aktif" as Unit["status"]};
const positionBlank={name:"",level:"Staf" as Position["level"],unitId:null as number|null,reportsToPositionId:null as number|null,sortOrder:0,status:"Aktif" as Position["status"]};

export default function OrganizationSettings(){
  const [employees,setEmployees]=useState<Employee[]>([]),[links,setLinks]=useState<Coordination[]>([]),[units,setUnits]=useState<Unit[]>([]),[positions,setPositions]=useState<Position[]>([]),[member,setMember]=useState(""),[coordUnit,setCoordUnit]=useState(""),[mode,setMode]=useState<"unit"|"position">("position"),[unitForm,setUnitForm]=useState(unitBlank),[positionForm,setPositionForm]=useState(positionBlank),[editing,setEditing]=useState<number|null>(null),[toast,setToast]=useState("");
  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2500)};
  const load=()=>fetch("/api/admin/organization").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setEmployees(data.employees||[]);setLinks(data.coordinations||[]);setUnits(data.units||[]);setPositions(data.positions||[])}).catch(error=>notify(error.message||"Struktur belum dapat dimuat"));
  useEffect(()=>{load()},[]);
  const commissioners=useMemo(()=>employees.filter(employee=>employee.position==="Anggota"),[employees]);
  const subbags=useMemo(()=>units.filter(unit=>unit.status==="Aktif"&&unit.type==="Subbagian"),[units]);
  const reset=()=>{setEditing(null);setUnitForm(unitBlank);setPositionForm(positionBlank)};
  const save=async()=>{const body=mode==="unit"?{kind:"unit",id:editing,...unitForm}:{kind:"position",id:editing,...positionForm};const response=await fetch("/api/admin/organization",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)return notify(data.error);notify(editing?"Struktur diperbarui":"Struktur ditambahkan");reset();load()};
  const editUnit=(unit:Unit)=>{setMode("unit");setEditing(unit.id);setUnitForm({name:unit.name,type:unit.type,parentId:unit.parentId,sortOrder:unit.sortOrder,status:unit.status})};
  const editPosition=(position:Position)=>{setMode("position");setEditing(position.id);setPositionForm({name:position.name,level:position.level,unitId:position.unitId,reportsToPositionId:position.reportsToPositionId,sortOrder:position.sortOrder,status:position.status})};
  const addCoordination=async()=>{if(!member||!coordUnit)return notify("Pilih Anggota dan Subbag");const response=await fetch("/api/admin/organization",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"coordination",commissionerEmployeeId:Number(member),unitSubsection:coordUnit})}),data=await response.json();if(!response.ok)return notify(data.error);notify("Garis koordinasi ditambahkan");load()};
  const removeCoordination=async(id:number)=>{await fetch(`/api/admin/organization?kind=coordination&id=${id}`,{method:"DELETE"});notify("Garis koordinasi dihapus");load()};
  const renderUnit=(parentId:number|null,depth=0):React.ReactNode=>units.filter(unit=>unit.parentId===parentId).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name)).map(unit=><div key={unit.id} className={`org-node ${unit.status==="Nonaktif"?"inactive":""}`} style={{marginLeft:Math.min(depth,5)*20}}><div className="org-branch"><i>{depth?"↳":"●"}</i><div><b>{unit.name}</b><span>{unit.type}</span></div><em>{unit.status}</em><button onClick={()=>editUnit(unit)}>Edit Unit</button></div><div style={{marginLeft:24}}>{positions.filter(position=>position.unitId===unit.id).sort((a,b)=>a.sortOrder-b.sortOrder).map(position=><div key={position.id} className={`org-branch ${position.status==="Nonaktif"?"inactive":""}`}><i>◇</i><div><b>{position.name}</b><span>{position.level} · {position.assignedEmployeeName||"Belum ditempati"}</span></div><em>{position.status}</em><button onClick={()=>editPosition(position)}>Edit Posisi</button></div>)}</div>{renderUnit(unit.id,depth+1)}</div>);
  return <section><div className="page-title"><div><p>SUMBER UTAMA ORGANISASI</p><h1>Pohon Organisasi</h1><span>Unit, posisi, atasan, dan penempatan pegawai terhubung dalam satu struktur.</span></div><div className="row-actions"><button onClick={()=>{reset();setMode("unit")}}>+ Unit</button><button className="primary" onClick={()=>{reset();setMode("position")}}>+ Posisi</button></div></div>
    <div className="org-layout"><article className="module-card org-tree-card"><span>STRUKTUR DEMO AKTIF</span><h3>{units.length} unit · {positions.length} posisi</h3><p>Posisi adalah slot jabatan. Pegawai ditempatkan melalui Form Data Pegawai.</p><div className="org-tree">{units.length?renderUnit(null):<div className="empty-state">Struktur belum tersedia.</div>}</div></article>
      <article className="module-card"><span>{editing?"EDIT":"TAMBAH"} {mode==="unit"?"UNIT":"POSISI"}</span><h3>{mode==="unit"?"Susunan unit parent–child":"Slot jabatan pada unit"}</h3>{mode==="unit"?<div className="module-form"><label>Nama unit<input value={unitForm.name} onChange={e=>setUnitForm({...unitForm,name:e.target.value})}/></label><label>Jenis<select value={unitForm.type} onChange={e=>setUnitForm({...unitForm,type:e.target.value})}>{["Lembaga","Komisioner","Sekretariat","Subbagian","Unit"].map(value=><option key={value}>{value}</option>)}</select></label><label>Parent<select value={unitForm.parentId||""} onChange={e=>setUnitForm({...unitForm,parentId:e.target.value?Number(e.target.value):null})}><option value="">Struktur teratas</option>{units.filter(unit=>unit.id!==editing).map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label>Urutan<input type="number" value={unitForm.sortOrder} onChange={e=>setUnitForm({...unitForm,sortOrder:Number(e.target.value)})}/></label><label>Status<select value={unitForm.status} onChange={e=>setUnitForm({...unitForm,status:e.target.value as Unit["status"]})}><option>Aktif</option><option>Nonaktif</option></select></label></div>:<div className="module-form"><label>Nama posisi<input value={positionForm.name} onChange={e=>setPositionForm({...positionForm,name:e.target.value})}/></label><label>Tingkat jabatan<select value={positionForm.level} onChange={e=>setPositionForm({...positionForm,level:e.target.value as Position["level"]})}>{["Ketua","Anggota","Sekretaris","Kasubag","Staf"].map(value=><option key={value}>{value}</option>)}</select></label><label>Unit penempatan<select value={positionForm.unitId||""} onChange={e=>setPositionForm({...positionForm,unitId:e.target.value?Number(e.target.value):null})}><option value="">Pilih unit</option>{units.filter(unit=>unit.status==="Aktif").map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label>Atasan posisi<select value={positionForm.reportsToPositionId||""} onChange={e=>setPositionForm({...positionForm,reportsToPositionId:e.target.value?Number(e.target.value):null})}><option value="">Tidak ada</option>{positions.filter(position=>position.id!==editing&&position.status==="Aktif").map(position=><option key={position.id} value={position.id}>{position.name}</option>)}</select></label><label>Urutan<input type="number" value={positionForm.sortOrder} onChange={e=>setPositionForm({...positionForm,sortOrder:Number(e.target.value)})}/></label><label>Status<select value={positionForm.status} onChange={e=>setPositionForm({...positionForm,status:e.target.value as Position["status"]})}><option>Aktif</option><option>Nonaktif</option></select></label></div>}<div className="org-form-actions">{editing&&<button onClick={reset}>Batal</button>}<button className="primary" onClick={save}>{editing?"Simpan Perubahan":"Tambahkan"}</button></div></article></div>
    <div className="org-grid coordination-section"><article className="module-card"><span>GARIS KOORDINASI SUBSTANTIF</span><h3>Anggota ↔ Subbag</h3><p>Ketua melihat seluruh pekerjaan lembaga. KUL tidak memerlukan garis koordinasi khusus.</p><div className="module-form"><label>Anggota<select value={member} onChange={e=>setMember(e.target.value)}><option value="">Pilih Anggota</option>{commissioners.map(employee=><option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></label><label>Subbag<select value={coordUnit} onChange={e=>setCoordUnit(e.target.value)}><option value="">Pilih Subbag</option>{subbags.map(unit=><option key={unit.id}>{unit.name}</option>)}</select></label><button className="primary" onClick={addCoordination}>Tambahkan Garis</button></div></article><article className="module-card"><span>HUBUNGAN AKTIF</span><h3>{links.length} garis koordinasi</h3><div className="coord-list">{links.map(link=><div key={link.id}><div><b>{employees.find(employee=>employee.id===link.commissionerEmployeeId)?.fullName||"Anggota"}</b><span>{link.unitSubsection}</span></div><button onClick={()=>removeCoordination(link.id)}>Hapus</button></div>)}</div></article></div>{toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </section>;
}
