"use client";
import {useEffect,useMemo,useState} from "react";
type Template={id:number;title:string;unit:string;frequency:string;generationDay:number;dueOffsetDays:number;startDate:string;status:"Aktif"|"Dijeda"|"Nonaktif";picEmails:string};
type Task={id:number;title:string;unit:string;picEmails:string;priority:string;outputType:string;sourcePerformanceAgreementId:number|null;sourcePerformanceIndicatorId:number|null;sourcePkLabel?:string;createdBy:string;approvalStatus:string;approvalNote:string;deadline:string;extendedDeadline:string;status:string;progress:number;output:string;notes:string;verificationStatus:string;recurringTemplateId:number|null};
type ProgressUpdate={id:number;employeeEmail:string;progress:number;outputRealization:string;completedActivities:string;obstacles:string;notes:string;createdAt:string};
type Assignee={id:number;fullName:string;email:string;position:string;unit:string;isSelf:boolean};type OrgUnit={id:number;name:string;type:string};
type PerformanceSource={agreementId:number;indicatorId:number;year:number;agreementTitle:string;agreementLevel:string;ownerName:string;ownerPosition:string;objective:string;indicator:string;target:string};
const fresh=()=>({mode:"Sekali" as "Sekali"|"Berulang",title:"",unit:"",picEmails:[] as string[],priority:"Sedang",outputType:"Dokumen",sourcePerformanceAgreementId:null as number|null,sourcePerformanceIndicatorId:null as number|null,deadline:"",output:"",notes:"",frequency:"Bulanan",generationDay:1,dueOffsetDays:7,startDate:new Date().toISOString().slice(0,10),endDate:"",verifierEmail:""});
const parsePics=(raw:string)=>{try{return JSON.parse(raw||"[]") as string[]}catch{return[]}};
const OUTPUT_CATEGORIES=[
 ["Dokumen","Surat, memo, berita acara, SOP, proposal"],
 ["Laporan","Laporan kegiatan, laporan keuangan, laporan progres"],
 ["Data","Database, rekap, daftar inventaris, data pegawai"],
 ["File spreadsheet","Excel perhitungan, anggaran, rekap transaksi"],
 ["Presentasi","PPT, bahan rapat, laporan visual"],
 ["Komunikasi","Email, pengumuman, surat dinas"],
 ["Arsip","Arsip fisik, folder digital, database dokumen"],
 ["Jadwal","Agenda rapat, timeline, jadwal kerja"],
 ["Hasil kegiatan","Rapat terlaksana, pengadaan selesai, kegiatan terdokumentasi"],
 ["Rekomendasi","Hasil analisis, evaluasi, usulan perbaikan"],
] as const;
export default function RecurringTaskManager(){
 const [tasks,setTasks]=useState<Task[]>([]),[templates,setTemplates]=useState<Template[]>([]),[assignees,setAssignees]=useState<Assignee[]>([]),[units,setUnits]=useState<OrgUnit[]>([]),[performanceSources,setPerformanceSources]=useState<PerformanceSource[]>([]),[form,setForm]=useState(fresh()),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<Task|null>(null),[canManageRecurring,setCanManageRecurring]=useState(false),[canCreate,setCanCreate]=useState(false),[canAdmin,setCanAdmin]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[q,setQ]=useState(""),[status,setStatus]=useState("Semua"),[unitFilter,setUnitFilter]=useState("Semua"),[priorityFilter,setPriorityFilter]=useState("Semua"),[typeFilter,setTypeFilter]=useState("Semua"),[deadlineFilter,setDeadlineFilter]=useState("Semua"),[page,setPage]=useState(1);
 const [currentEmail,setCurrentEmail]=useState(""),[progressTask,setProgressTask]=useState<Task|null>(null),[progressHistory,setProgressHistory]=useState<ProgressUpdate[]>([]),[progressForm,setProgressForm]=useState({progress:0,outputRealization:"",completedActivities:"",obstacles:"",notes:""});
 const [canApproveTaskIds,setCanApproveTaskIds]=useState<number[]>([]);
 const load=()=>Promise.all([fetch("/api/recurring-tasks"),fetch("/api/task-assignees"),fetch("/api/monitoring"),fetch("/api/task-performance-sources")]).then(async([tr,ar,mr,pr])=>{const t=await tr.json(),a=await ar.json(),m=await mr.json(),p=await pr.json();if(tr.ok){setTemplates(t.templates||[]);setCanManageRecurring(Boolean(t.canManage))}if(ar.ok){setAssignees(a.assignees||[]);setUnits(a.units||[]);setCanCreate(Boolean(a.canCreate));setCanAdmin(Boolean(a.canAdministerTasks));setCurrentEmail(a.currentEmail||"")}if(mr.ok){setTasks(m.tasks||[]);setCanApproveTaskIds(m.canApproveTaskIds||[])}if(pr.ok)setPerformanceSources(p.sources||[])});useEffect(()=>{load()},[]);
 const today=new Date().toISOString().slice(0,10),deadlineOf=(task:Task)=>task.extendedDeadline||task.deadline||"";
 const filtered=useMemo(()=>tasks.filter(t=>{const deadline=deadlineOf(t),isCompleted=t.status==="Selesai"||t.progress>=100,isOverdue=Boolean(deadline&&deadline<today&&!isCompleted);return (!q||t.title.toLowerCase().includes(q.toLowerCase())||t.unit.toLowerCase().includes(q.toLowerCase()))&&(status==="Semua"||t.status===status)&&(unitFilter==="Semua"||t.unit===unitFilter)&&(priorityFilter==="Semua"||t.priority===priorityFilter)&&(typeFilter==="Semua"||(typeFilter==="Berulang")===Boolean(t.recurringTemplateId))&&(deadlineFilter==="Semua"||(deadlineFilter==="Melewati deadline"&&isOverdue)||(deadlineFilter==="Belum melewati deadline"&&Boolean(deadline)&&!isOverdue)||(deadlineFilter==="Tanpa deadline"&&!deadline))}),[tasks,q,status,unitFilter,priorityFilter,typeFilter,deadlineFilter,today]);
 useEffect(()=>setPage(1),[q,status,unitFilter,priorityFilter,typeFilter,deadlineFilter]);const pages=Math.max(1,Math.ceil(filtered.length/25)),rows=filtered.slice((page-1)*25,page*25);const active=tasks.filter(t=>t.status!=="Selesai"&&t.progress<100),completed=tasks.filter(t=>t.status==="Selesai"||t.progress>=100),overdue=active.filter(t=>Boolean(deadlineOf(t)&&deadlineOf(t)<today)),average=tasks.length?Math.round(tasks.reduce((s,t)=>s+t.progress,0)/tasks.length):0;
 const togglePic=(email:string)=>setForm({...form,picEmails:form.picEmails.includes(email)?form.picEmails.filter(x=>x!==email):[...form.picEmails,email]});
 const save=async()=>{setSaving(true);setMessage("");const recurring=form.mode==="Berulang",r=await fetch(recurring?"/api/recurring-tasks":"/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error||"To-Do belum tersimpan");return}setForm(fresh());setShowForm(false);setMessage(recurring?"Template berulang berhasil diaktifkan.":"To-Do berhasil dibuat.");load()};
 const saveEdit=async()=>{if(!editing)return;setSaving(true);const r=await fetch(canAdmin?"/api/admin/tasks":"/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...editing,action:canAdmin?undefined:"edit_unstarted",picEmails:parsePics(editing.picEmails)})}),d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error||"Perubahan belum tersimpan");return}setEditing(null);setMessage("To-Do berhasil diperbarui.");load()};
 const remove=async(task:Task)=>{const reason=prompt(`Alasan menghapus To-Do “${task.title}” (minimal 5 karakter):`);if(!reason||reason.trim().length<5){setMessage("Penghapusan dibatalkan. Alasan minimal 5 karakter.");return}const r=await fetch(`/api/admin/tasks?id=${task.id}&reason=${encodeURIComponent(reason.trim())}`,{method:"DELETE"});const d=await r.json();if(r.ok){setMessage("To-Do berhasil dihapus dan dicatat dalam audit.");load()}else setMessage(d.error||"To-Do belum dapat dihapus.")};
 const changeTemplate=async(t:Template,next:Template["status"])=>{await fetch("/api/recurring-tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:t.id,status:next})});load()};
 const canUpdate=(task:Task)=>parsePics(task.picEmails).map(x=>x.toLowerCase()).includes(currentEmail.toLowerCase());
 const canEditUnstarted=(task:Task)=>task.createdBy.toLowerCase()===currentEmail.toLowerCase()&&task.status==="Baru"&&task.progress===0;
 const sourceFor=(task:Task)=>performanceSources.find(source=>source.indicatorId===task.sourcePerformanceIndicatorId);
 const openProgress=async(task:Task)=>{setProgressTask(task);setProgressForm({progress:task.progress,outputRealization:task.output||"",completedActivities:"",obstacles:"",notes:""});setProgressHistory([]);const r=await fetch(`/api/tasks?taskId=${task.id}`);if(r.ok){const d=await r.json();setProgressHistory(d.history||[])}};
 const saveProgress=async()=>{if(!progressTask)return;if(!progressForm.completedActivities.trim()){setMessage("Kegiatan yang sudah dilaksanakan wajib diisi.");return}if(progressForm.progress===100&&!progressForm.outputRealization.trim()){setMessage("Realisasi output wajib diisi untuk progres 100%.");return}setSaving(true);const r=await fetch("/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:progressTask.id,...progressForm})}),d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error||"Progress belum tersimpan.");return}setProgressTask(null);setMessage(progressForm.progress===100?"Progress 100% dikirim untuk verifikasi atasan.":"Progress berhasil diperbarui.");load()};
 const taskApproval=async(task:Task,action:"request_approval"|"approve"|"reject"|"needs_revision"|"verify_complete"|"verify_revision")=>{const needsNote=["reject","needs_revision","verify_revision"].includes(action),decisionNote=needsNote?(prompt(action==="reject"?"Alasan penolakan:":"Catatan perbaikan:")||""):"";if(needsNote&&!decisionNote.trim())return;const r=await fetch("/api/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:task.id,action,decisionNote})}),d=await r.json();setMessage(r.ok?(action==="request_approval"?"To-Do telah diajukan kepada atasan.":action==="verify_complete"?"Pekerjaan telah diverifikasi dan dinyatakan selesai.":action==="verify_revision"?"Pekerjaan dikembalikan untuk perbaikan.":"Keputusan persetujuan berhasil disimpan."):(d.error||"Tindakan belum berhasil."));if(r.ok)load()};
 const hasActions=canAdmin||tasks.some(t=>canUpdate(t)||canApproveTaskIds.includes(t.id)||canEditUnstarted(t));
 return <section className="todo-database-page"><div className="page-title"><div><p>DATABASE PEKERJAAN</p><h1>To-Do & Progres</h1><span>Maksimal 25 baris per halaman · sesuai cakupan kewenangan.</span></div>{canCreate&&<button className="primary" onClick={()=>{setMessage("");setShowForm(true)}}>＋ Buat To-Do</button>}</div>{message&&<div className="todo-success">{message}</div>}
 <div className="todo-summary progress-report"><article><b>{tasks.length}</b><span>Total pekerjaan</span></article><article><b>{active.length}</b><span>Masih aktif</span></article><article><b>{completed.length}</b><span>Selesai</span></article><article><b>{average}%</b><span>Rata-rata progres</span></article><article className={`${overdue.length?"warning ":""}filter-link`} role="button" tabIndex={0} aria-label={`Tampilkan ${overdue.length} To-Do yang melewati deadline`} onClick={()=>setDeadlineFilter("Melewati deadline")} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setDeadlineFilter("Melewati deadline")}}><b>{overdue.length}</b><span>Melewati deadline · klik untuk melihat</span></article></div>
 <div className="todo-toolbar advanced"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari pekerjaan atau unit..."/><select aria-label="Filter jenis To-Do" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}>{["Semua","Sekali","Berulang"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter unit" value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option>Semua</option>{Array.from(new Set(tasks.map(t=>t.unit))).sort().map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter prioritas" value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}>{["Semua","Rendah","Sedang","Tinggi","Urgent"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}>{["Semua","Baru","Ditolak","Dikerjakan","Menunggu Verifikasi","Verifikasi Final","Perbaikan","Selesai"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter deadline" value={deadlineFilter} onChange={e=>setDeadlineFilter(e.target.value)}>{["Semua","Melewati deadline","Belum melewati deadline","Tanpa deadline"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="employee-table-wrap"><table className="employee-table todo-table"><thead><tr><th>No.</th><th>Uraian</th><th>Jenis</th><th>PIC</th><th>Unit</th><th>Prioritas</th><th>Deadline</th><th>Status</th><th>Progress</th><th>Output</th><th>Catatan</th><th>Persetujuan/Verifikasi</th>{hasActions&&<th>Aksi</th>}</tr></thead><tbody>{rows.length?rows.map((t,i)=>{const pk=sourceFor(t),pkLabel=t.sourcePkLabel||(pk?`${pk.ownerPosition} · ${pk.indicator}`:"");return <tr key={t.id}><td>{(page-1)*25+i+1}</td><td><b>{t.title}</b>{pkLabel&&<small className="task-pk-source">PK: {pkLabel}</small>}</td><td><span className="access-badge">{t.recurringTemplateId?"Berulang":"Sekali"}</span></td><td>{parsePics(t.picEmails).length} pegawai</td><td>{t.unit}</td><td>{t.priority}</td><td>{t.extendedDeadline||t.deadline||"—"}</td><td><span className="status-badge">{t.status}</span></td><td><div className="table-progress"><i style={{width:`${t.progress}%`}}/></div>{t.progress}%</td><td>{t.output||"—"}</td><td>{t.notes||"—"}</td><td><b>{t.approvalStatus||"Tidak Perlu Persetujuan"}</b><small>{t.approvalNote||t.verificationStatus}</small></td>{hasActions&&<td><div className="row-actions">{canUpdate(t)&&t.approvalStatus==="Draft"&&<button onClick={()=>taskApproval(t,"request_approval")}>Minta Persetujuan</button>}{canUpdate(t)&&!["Draft","Menunggu Persetujuan","Ditolak"].includes(t.approvalStatus)&&t.status!=="Selesai"&&t.status!=="Verifikasi Final"&&<button onClick={()=>{setMessage("");openProgress(t)}}>Update Progress</button>}{canApproveTaskIds.includes(t.id)&&t.approvalStatus==="Menunggu Persetujuan"&&<><button onClick={()=>taskApproval(t,"approve")}>Setujui</button><button onClick={()=>taskApproval(t,"needs_revision")}>Perbaikan</button><button className="danger" onClick={()=>taskApproval(t,"reject")}>Tolak</button></>}{canApproveTaskIds.includes(t.id)&&t.status==="Verifikasi Final"&&<><button onClick={()=>taskApproval(t,"verify_complete")}>Verifikasi Selesai</button><button onClick={()=>taskApproval(t,"verify_revision")}>Minta Perbaikan</button></>}{!canAdmin&&canEditUnstarted(t)&&<button onClick={()=>{setMessage("");setEditing({...t})}}>Edit sebelum dikerjakan</button>}{canAdmin&&<><button onClick={()=>{setMessage("");setEditing({...t})}}>Edit</button><button className="danger" onClick={()=>remove(t)}>Hapus</button></>}</div></td>}</tr>}):<tr><td colSpan={hasActions?13:12} className="empty-state">Belum ada To-Do yang sesuai dengan filter.</td></tr>}</tbody></table></div>
 <div className="pagination"><span>Menampilkan {filtered.length?((page-1)*25+1):0}–{Math.min(page*25,filtered.length)} dari {filtered.length}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>Sebelumnya</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Berikutnya</button></div></div>
 {templates.length>0&&<section className="template-manager"><div><b>Template To-Do Berulang</b><span>{templates.length} template</span></div><div className="template-list compact">{templates.map(t=><article key={t.id}><div><b>{t.title}</b><span>{t.unit} · {t.frequency} · hari ke-{t.generationDay}</span></div><em className={t.status.toLowerCase()}>{t.status}</em>{canManageRecurring&&<select value={t.status} onChange={e=>changeTemplate(t,e.target.value as Template["status"])}><option>Aktif</option><option>Dijeda</option><option>Nonaktif</option></select>}</article>)}</div></section>}
 {showForm&&<CreateModal form={form} setForm={setForm} units={units} assignees={assignees} performanceSources={performanceSources} canRecurring={canManageRecurring} togglePic={togglePic} close={()=>setShowForm(false)} save={save} saving={saving} message={message}/>} {editing&&<EditModal task={editing} setTask={setEditing} units={units} assignees={assignees} performanceSources={performanceSources} close={()=>setEditing(null)} save={saveEdit} saving={saving} message={message}/>} {progressTask&&<ProgressModal task={progressTask} form={progressForm} setForm={setProgressForm} history={progressHistory} close={()=>setProgressTask(null)} save={saveProgress} saving={saving}/>}</section>;
}
function ProgressModal({task,form,setForm,history,close,save,saving}:any){return <div className="modal-backdrop" onMouseDown={close}><div className="modal progress-update-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><span>UPDATE PROGRESS TO-DO</span><Title title={task.title} close={close}/><p>Progress 100% akan berstatus Verifikasi Final sampai diperiksa atasan.</p><div className="module-form two-col"><label>Progress (%)<input type="number" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label><label>Status sistem<input value={form.progress===100?"Verifikasi Final":"Dikerjakan"} disabled/></label><label className="wide">Kegiatan yang sudah dilaksanakan<textarea rows={3} value={form.completedActivities} onChange={e=>setForm({...form,completedActivities:e.target.value})}/></label><label className="wide">Realisasi output<textarea rows={3} value={form.outputRealization} onChange={e=>setForm({...form,outputRealization:e.target.value})}/></label><label className="wide">Kendala<textarea rows={2} value={form.obstacles} onChange={e=>setForm({...form,obstacles:e.target.value})}/></label><label className="wide">Catatan tambahan<textarea rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{history.length>0&&<div className="progress-history"><h4>Riwayat Pembaruan</h4>{history.slice(0,5).map((row:ProgressUpdate)=><article key={row.id}><b>{row.progress}%</b><div><strong>{row.completedActivities}</strong><small>{row.employeeEmail} · {new Date(row.createdAt+"Z").toLocaleString("id-ID")}</small>{row.obstacles&&<small>Kendala: {row.obstacles}</small>}</div></article>)}</div>}<Actions close={close} save={save} saving={saving} label="Simpan Progress"/></div></div>}
function CreateModal({form,setForm,units,assignees,performanceSources,canRecurring,togglePic,close,save,saving,message}:any){return <div className="modal-backdrop" onMouseDown={close}><div className="modal todo-form-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><span>FORM TO-DO</span><Title title="Buat pekerjaan baru" close={close}/><div className="task-mode"><button className={form.mode==="Sekali"?"active":""} onClick={()=>setForm({...form,mode:"Sekali"})}><b>Sekali</b><small>Dibuat satu kali</small></button>{canRecurring&&<button className={form.mode==="Berulang"?"active":""} onClick={()=>setForm({...form,mode:"Berulang"})}><b>Berulang</b><small>Otomatis per periode</small></button>}</div><div className="module-form two-col"><BaseFields value={form} setValue={setForm} units={units}/>{form.mode==="Sekali"?<label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label>:<><label>Frekuensi<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}>{["Mingguan","Bulanan","Triwulan","Semester"].map(x=><option key={x}>{x}</option>)}</select></label><label>Hari ke-<input type="number" min="1" max="28" value={form.generationDay} onChange={e=>setForm({...form,generationDay:Number(e.target.value)})}/></label><label>Tenggat +hari<input type="number" min="0" value={form.dueOffsetDays} onChange={e=>setForm({...form,dueOffsetDays:Number(e.target.value)})}/></label><label>Mulai<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Selesai opsional<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></>}<PerformanceSourcePicker value={form.sourcePerformanceIndicatorId} sources={performanceSources} change={(source:PerformanceSource|null)=>setForm({...form,sourcePerformanceAgreementId:source?.agreementId||null,sourcePerformanceIndicatorId:source?.indicatorId||null})}/><OutputCategoryPicker value={form.outputType} change={(outputType:string)=>setForm({...form,outputType})}/>{form.mode==="Sekali"&&<label className="wide">Output yang diharapkan<input value={form.output} onChange={e=>setForm({...form,output:e.target.value})}/></label>}<label className="wide">Catatan<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><PicPicker emails={form.picEmails} assignees={assignees} toggle={togglePic}/></div><Actions close={close} save={save} saving={saving} label={form.mode==="Sekali"?"Buat To-Do":"Aktifkan Berulang"} message={message}/></div></div>}
function EditModal({task,setTask,units,assignees,performanceSources,close,save,saving,message}:any){const emails=parsePics(task.picEmails),toggle=(email:string)=>setTask({...task,picEmails:JSON.stringify(emails.includes(email)?emails.filter((x:string)=>x!==email):[...emails,email])});return <div className="modal-backdrop" onMouseDown={close}><div className="modal todo-form-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><span>SUPER ADMIN · EDIT TO-DO</span><Title title="Perbaiki data pekerjaan" close={close}/><div className="module-form two-col"><BaseFields value={task} setValue={setTask} units={units}/><label>Deadline<input type="date" value={task.deadline||""} onChange={e=>setTask({...task,deadline:e.target.value})}/></label><label>Perpanjangan deadline<input type="date" value={task.extendedDeadline||""} onChange={e=>setTask({...task,extendedDeadline:e.target.value})}/></label><label>Status<select value={task.status} onChange={e=>setTask({...task,status:e.target.value})}>{["Baru","Ditolak","Dikerjakan","Menunggu Verifikasi","Verifikasi Final","Perbaikan","Selesai"].map(x=><option key={x}>{x}</option>)}</select></label><label>Progress (%)<input type="number" min="0" max="100" value={task.progress} onChange={e=>setTask({...task,progress:Number(e.target.value)})}/></label><label>Verifikasi<select value={task.verificationStatus} onChange={e=>setTask({...task,verificationStatus:e.target.value})}><option>Belum Diverifikasi</option><option>Menunggu Verifikasi</option><option>Terverifikasi</option><option>Perlu Perbaikan</option></select></label><PerformanceSourcePicker value={task.sourcePerformanceIndicatorId} sources={performanceSources} change={(source:PerformanceSource|null)=>setTask({...task,sourcePerformanceAgreementId:source?.agreementId||null,sourcePerformanceIndicatorId:source?.indicatorId||null})}/><OutputCategoryPicker value={task.outputType||"Dokumen"} change={(outputType:string)=>setTask({...task,outputType})}/><label className="wide">Output<input value={task.output||""} onChange={e=>setTask({...task,output:e.target.value})}/></label><label className="wide">Catatan<textarea rows={3} value={task.notes||""} onChange={e=>setTask({...task,notes:e.target.value})}/></label><PicPicker emails={emails} assignees={assignees} toggle={toggle}/></div><Actions close={close} save={save} saving={saving} label="Simpan Perubahan" message={message}/></div></div>}
function BaseFields({value,setValue,units}:any){return <><label>Uraian<input value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>Unit/Subbagian<select value={value.unit} onChange={e=>setValue({...value,unit:e.target.value})}><option value="">Pilih Struktur Organisasi</option>{units.map((u:OrgUnit)=><option key={u.id} value={u.name}>{u.name} · {u.type}</option>)}</select></label><label>Prioritas<select value={value.priority} onChange={e=>setValue({...value,priority:e.target.value})}>{["Rendah","Sedang","Tinggi","Urgent"].map(x=><option key={x}>{x}</option>)}</select></label></>}
function PicPicker({emails,assignees,toggle}:any){return <fieldset className="pic-picker wide"><legend>PIC/Penanggung Jawab</legend><div>{assignees.map((p:Assignee)=><label key={p.id} className={emails.includes(p.email)?"selected":""}><input type="checkbox" checked={emails.includes(p.email)} onChange={()=>toggle(p.email)}/><span><b>{p.fullName}{p.isSelf?" (Saya)":""}</b><small>{p.position||"Pegawai"} · {p.unit}</small></span></label>)}</div></fieldset>}
function PerformanceSourcePicker({value,sources,change}:any){return <label className="wide pk-source-field">Sumber Perjanjian Kinerja<select value={value||""} onChange={e=>change(sources.find((source:PerformanceSource)=>source.indicatorId===Number(e.target.value))||null)}><option value="">Tidak terhubung dengan PK</option>{sources.map((source:PerformanceSource)=><option key={source.indicatorId} value={source.indicatorId}>{source.year} · {source.ownerPosition} — {source.objective} — {source.indicator} ({source.target})</option>)}</select><small>Hanya PK yang berada pada jalur koordinasi Anda yang tersedia.</small></label>}
function OutputCategoryPicker({value,change}:any){return <fieldset className="output-category-picker wide"><legend>Kategori Pekerjaan</legend><p>Pilih kategori berdasarkan bentuk output yang akan dihasilkan.</p><div>{OUTPUT_CATEGORIES.map(([name,example])=><label key={name} className={value===name?"selected":""}><input type="radio" name="output-category" checked={value===name} onChange={()=>change(name)}/><span><b>{name}</b><small>{example}</small></span></label>)}</div></fieldset>}
function Title({title,close}:any){return <div className="modal-title-row"><div><h3>{title}</h3><p>Perubahan disimpan ke database To-Do.</p></div><button aria-label="Tutup" onClick={close}>×</button></div>}
function Actions({close,save,saving,label,message}:any){return <>{message&&<p className="form-message">{message}</p>}<div className="modal-actions"><button onClick={close}>Batal</button><button className="primary" onClick={save} disabled={saving}>{saving?"Menyimpan...":label}</button></div></>}
