"use client";
import { useEffect, useState } from "react";

type SecurityData={scope:string;canRevoke:boolean;canExport:boolean;metrics:{activeSessions:number;denied24h:number;changes7d:number;lastBackup:string|null};sessions:Array<{email:string;device:string;ipMasked:string;createdAt:string;lastActivityAt:string;expiresAt:string}>;audits:Array<{id:number;actorEmail:string;actorRole:string;action:string;resourceType:string;resourceId:string;status:string;reason:string;createdAt:string}>;backups:Array<{id:number;requestedBy:string;recordCount:number;status:string;createdAt:string}>};
const date=(value:string|null)=>value?new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"}):"Belum ada";
export default function SecurityCenter(){
  const [data,setData]=useState<SecurityData|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
  const load=()=>fetch("/api/admin/security").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setMessage(e.message||"Data keamanan belum dapat dimuat")).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);
  const revoke=async(email:string)=>{const r=await fetch(`/api/admin/security?email=${encodeURIComponent(email)}`,{method:"DELETE"});const d=await r.json();setMessage(r.ok?"Sesi berhasil dicabut":d.error);if(r.ok)load()};
  if(loading)return <section className="security-page"><div className="page-title"><div><p>KEAMANAN SISTEM</p><h1>Memuat Dashboard Keamanan…</h1></div></div></section>;
  if(!data)return <section className="security-page"><div className="page-title"><div><p>KEAMANAN SISTEM</p><h1>Dashboard tidak tersedia</h1><span>{message}</span></div></div></section>;
  return <section className="security-page">
    <div className="page-title"><div><p>KEAMANAN SISTEM</p><h1>Dashboard Keamanan</h1><span>Cakupan: {data.scope}. Audit log tidak dapat diedit atau dihapus dari aplikasi.</span></div>{data.canExport&&<a className="security-export" href="/api/admin/security/export">Unduh Backup JSON</a>}</div>
    {message&&<div className="security-message">{message}</div>}
    <div className="security-metrics"><article><b>{data.metrics.activeSessions}</b><span>Sesi aktif</span></article><article><b>{data.metrics.denied24h}</b><span>Akses ditolak 24 jam</span></article><article><b>{data.metrics.changes7d}</b><span>Aktivitas 7 hari</span></article><article><b>{date(data.metrics.lastBackup)}</b><span>Backup terakhir</span></article></div>
    {data.canRevoke&&<div className="security-panel"><div className="security-heading"><div><h2>Sesi Aktif</h2><p>Satu akun hanya memiliki satu sesi aktif.</p></div></div><div className="security-table"><table><thead><tr><th>Akun</th><th>Perangkat</th><th>IP</th><th>Aktivitas terakhir</th><th>Kedaluwarsa</th><th>Aksi</th></tr></thead><tbody>{data.sessions.length?data.sessions.map(s=><tr key={s.email}><td>{s.email}</td><td>{s.device}</td><td>{s.ipMasked||"—"}</td><td>{date(s.lastActivityAt)}</td><td>{date(s.expiresAt)}</td><td><button onClick={()=>revoke(s.email)}>Cabut sesi</button></td></tr>):<tr><td colSpan={6}>Belum ada sesi aktif.</td></tr>}</tbody></table></div></div>}
    <div className="security-panel"><div className="security-heading"><div><h2>Audit Keamanan</h2><p>Login, penolakan akses, perubahan penting, dan ekspor data.</p></div></div><div className="security-table"><table><thead><tr><th>Waktu</th><th>Pengguna</th><th>Tindakan</th><th>Objek</th><th>Status</th><th>Keterangan</th></tr></thead><tbody>{data.audits.length?data.audits.map(a=><tr key={a.id}><td>{date(a.createdAt)}</td><td>{a.actorEmail}<small>{a.actorRole}</small></td><td>{a.action}</td><td>{a.resourceType}{a.resourceId?` · ${a.resourceId}`:""}</td><td><span className={`security-status ${a.status.toLowerCase()}`}>{a.status}</span></td><td>{a.reason||"—"}</td></tr>):<tr><td colSpan={6}>Belum ada catatan audit.</td></tr>}</tbody></table></div></div>
    <div className="security-panel"><div className="security-heading"><div><h2>Riwayat Backup Manual</h2><p>Backup menyertakan data bisnis, tetapi tidak menyertakan token sesi.</p></div></div><div className="security-table"><table><thead><tr><th>Waktu</th><th>Pembuat</th><th>Jumlah record</th><th>Status</th></tr></thead><tbody>{data.backups.length?data.backups.map(b=><tr key={b.id}><td>{date(b.createdAt)}</td><td>{b.requestedBy}</td><td>{b.recordCount}</td><td>{b.status}</td></tr>):<tr><td colSpan={4}>Belum ada backup manual.</td></tr>}</tbody></table></div></div>
  </section>;
}
